# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-21 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import records.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BSInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant', models.CharField(blank=True, default='-', max_length=20, null=True, verbose_name='申请人')),
                ('contact', models.CharField(blank=True, max_length=20, null=True, verbose_name='联系方式')),
                ('device_number', models.CharField(max_length=30, verbose_name='SN号码')),
                ('device_number_detail', models.TextField(blank=True, null=True, verbose_name='SN号码详情')),
                ('state', models.IntegerField(choices=[(0, '申请中'), (1, '已审批通过'), (2, '审批不通过')], default=0, verbose_name='申请状态')),
                ('application_date', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('approval_date', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('upload_file', models.FileField(blank=True, null=True, upload_to=records.models.bs_upload_to, verbose_name='文件上传')),
                ('is_download', models.IntegerField(choices=[(0, '未下载'), (1, '已下载')], default=0, verbose_name='下载状态')),
            ],
            options={
                'verbose_name_plural': 'BS申请信息',
                'verbose_name': 'BS申请信息',
                'ordering': ['-applicant'],
            },
        ),
        migrations.CreateModel(
            name='CSInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant', models.CharField(blank=True, default='-', max_length=20, null=True, verbose_name='申请人')),
                ('contact', models.CharField(blank=True, max_length=20, null=True, verbose_name='联系方式')),
                ('device_number', models.CharField(max_length=30, verbose_name='SN号码')),
                ('is_sync_wx', models.IntegerField(choices=[(0, '未同步'), (1, '已同步')], default=0, verbose_name='是否同步企业微信')),
                ('is_sync_ff', models.IntegerField(choices=[(0, '未同步'), (1, '已同步')], default=0, verbose_name='是否同步服服后台')),
                ('deal_tag_wx', models.IntegerField(choices=[(0, '未处理'), (1, '已处理')], default=0, verbose_name='企业处理标志')),
                ('deal_tag_ff', models.IntegerField(choices=[(0, '未处理'), (1, '已处理')], default=0, verbose_name='服服处理标志')),
            ],
            options={
                'verbose_name_plural': '固件记录',
                'verbose_name': '固件记录',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.CharField(max_length=30, unique=True, verbose_name='model_id')),
                ('device_name', models.CharField(max_length=20, verbose_name='设备类型名')),
                ('del_tag', models.IntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否删除')),
                ('upload_file', models.FileField(blank=True, null=True, upload_to=records.models.upload_to, verbose_name='文件上传')),
            ],
            options={
                'verbose_name_plural': '设备类型',
                'verbose_name': '设备类型',
            },
        ),
        migrations.CreateModel(
            name='InterfaceLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.IntegerField(verbose_name='状态码')),
                ('status_msg', models.TextField(verbose_name='状态信息')),
                ('model_id', models.CharField(blank=True, max_length=30, null=True, verbose_name='model_id')),
                ('device_sn', models.CharField(blank=True, max_length=20, null=True, verbose_name='设备SN')),
                ('create_time', models.IntegerField(blank=True, null=True, verbose_name='创建时间')),
                ('secret_no', models.CharField(blank=True, max_length=50, null=True)),
                ('device_id', models.BigIntegerField(blank=True, null=True)),
                ('qr_code', models.CharField(blank=True, max_length=200, null=True)),
                ('platform', models.IntegerField(choices=[(0, '企业微信'), (1, '服服')], verbose_name='接口平台')),
                ('deal_time', models.DateTimeField(auto_now_add=True, verbose_name='处理时间')),
            ],
            options={
                'verbose_name_plural': '接口日志',
                'verbose_name': '接口日志',
                'ordering': ['-deal_time'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='device',
            unique_together=set([('device_name',)]),
        ),
        migrations.AddField(
            model_name='csinfo',
            name='device_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.Device', verbose_name='设备型号'),
        ),
        migrations.AddField(
            model_name='bsinfo',
            name='device_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.Device', verbose_name='设备型号'),
        ),
        migrations.AlterUniqueTogether(
            name='csinfo',
            unique_together=set([('device_number', 'device_type')]),
        ),
    ]
