# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-07 18:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oauth_type', models.CharField(default='wechat', max_length=8, verbose_name='认证类型')),
                ('oauth_id', models.CharField(max_length=28, verbose_name='openid')),
                ('oauth_union_id', models.CharField(max_length=29, verbose_name='union_id')),
                ('access_token', models.CharField(max_length=512)),
                ('expires_in', models.IntegerField(default=0)),
                ('random_str', models.CharField(blank=True, max_length=8, null=True)),
                ('md5', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'verbose_name_plural': '认证信息',
                'verbose_name': '认证信息',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=32, verbose_name='昵称')),
                ('sex', models.SmallIntegerField(choices=[(1, '男'), (2, '女')], verbose_name='性别')),
                ('province', models.CharField(max_length=16, verbose_name='省份')),
                ('city', models.CharField(max_length=16, verbose_name='城市')),
                ('country', models.CharField(max_length=8, verbose_name='国家')),
            ],
            options={
                'verbose_name_plural': '用户资料',
                'verbose_name': '用户资料',
            },
        ),
        migrations.AddField(
            model_name='oauth',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserProfile'),
        ),
    ]
